#!/usr/bin/env python3
"""Regenerate the docs/STATE.md task board from tasks/*.md frontmatter.

The task board table in STATE.md is generated, never hand-edited. This script
is the single source of truth for it, reading the frontmatter of every
tasks/T-*.md file (stdlib only, no PyYAML).

Usage:
  forge-state.py            print the generated board to stdout
  forge-state.py --write    replace the marker block in docs/STATE.md
  forge-state.py --check    exit 2 if docs/STATE.md has drifted (CI-friendly)

STATE.md must contain the marker pair:
  <!-- forge:task-board:begin -->
  <!-- forge:task-board:end -->
Everything between them is owned by this script; prose outside is yours.
"""

import re
import sys
from pathlib import Path

BEGIN = "<!-- forge:task-board:begin -->"
END = "<!-- forge:task-board:end -->"


def repo_root() -> Path:
    # framework/scripts/forge-state.py -> repo root is two levels up
    return Path(__file__).resolve().parent.parent.parent


def parse_frontmatter(text: str) -> dict:
    """Parse the minimal YAML subset used by TASK_TEMPLATE.md frontmatter."""
    m = re.match(r"\A---\s*\n(.*?)\n---\s*(\n|\Z)", text, re.DOTALL)
    if not m:
        return {}
    data: dict = {}
    key = None
    for line in m.group(1).splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        block_item = re.match(r"\s+-\s+(.*)$", line)
        if block_item and key is not None:
            if not isinstance(data.get(key), list):
                data[key] = []
            data[key].append(_scalar(block_item.group(1)))
            continue
        kv = re.match(r"([A-Za-z][\w-]*):\s*(.*)$", line)
        if not kv:
            continue
        key, raw = kv.group(1), kv.group(2).strip()
        if raw == "":
            data[key] = []  # block list follows (or empty)
        elif raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            data[key] = [_scalar(x) for x in inner.split(",")] if inner else []
        else:
            data[key] = _scalar(raw)
    return data


def _scalar(raw: str) -> str:
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        raw = raw[1:-1]
    return raw


def load_tasks(root: Path) -> list:
    tasks = []
    for path in sorted((root / "tasks").glob("T-*.md")):
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        if not fm.get("id"):
            print(f"warning: {path.name} has no parseable frontmatter, skipped",
                  file=sys.stderr)
            continue
        tasks.append(fm)
    return tasks


def ready_set(tasks: list) -> list:
    done = {t["id"] for t in tasks if t.get("status") == "done"}
    ready = []
    for t in tasks:
        if t.get("status") not in ("pending", "ready"):
            continue
        deps = t.get("depends_on") or []
        if all(d in done for d in deps):
            ready.append(t["id"])
    return ready


def render(tasks: list) -> str:
    lines = [
        "| ID | Title | Status | Wave | Model | Owns (top path) |",
        "|----|-------|--------|------|-------|-----------------|",
    ]
    for t in tasks:
        owns = t.get("owns") or []
        owns_cell = owns[0] + (" …" if len(owns) > 1 else "") if owns else "—"
        lines.append(
            "| {id} | {title} | {status} | {wave} | {model} | {owns} |".format(
                id=t.get("id", "?"),
                title=t.get("title", "?"),
                status=t.get("status", "?"),
                wave=t.get("wave", "?"),
                model=t.get("model", "?"),
                owns=owns_cell,
            )
        )
    ready = ready_set(tasks)
    lines.append("")
    lines.append("**Ready now:** " + (", ".join(ready) if ready else "none"))
    lines.append("")
    lines.append("_Generated by `framework/scripts/forge-state.py` — do not hand-edit this block._")
    return "\n".join(lines)


def splice(state_text: str, board: str) -> str:
    if BEGIN not in state_text or END not in state_text:
        raise SystemExit(
            f"error: docs/STATE.md is missing the marker pair\n  {BEGIN}\n  {END}\n"
            "Add them around the task board section, then rerun."
        )
    pre = state_text.split(BEGIN)[0]
    post = state_text.split(END, 1)[1]
    return f"{pre}{BEGIN}\n{board}\n{END}{post}"


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else ""
    root = repo_root()
    tasks = load_tasks(root)
    if not tasks:
        print("no tasks/T-*.md files found; nothing to do", file=sys.stderr)
        return 0
    board = render(tasks)
    state_path = root / "docs" / "STATE.md"

    if mode == "--write":
        state_path.write_text(splice(state_path.read_text(encoding="utf-8"), board),
                              encoding="utf-8")
        print(f"wrote task board ({len(tasks)} tasks) to {state_path}")
        return 0
    if mode == "--check":
        current = state_path.read_text(encoding="utf-8")
        if splice(current, board) != current:
            print("STATE.md task board has drifted from tasks/*.md frontmatter.\n"
                  "Run: python3 framework/scripts/forge-state.py --write",
                  file=sys.stderr)
            return 2
        print("STATE.md task board is in sync")
        return 0
    print(board)
    return 0


if __name__ == "__main__":
    sys.exit(main())
